document.writeln("");
document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title></title>");
document.writeln("<!-- <script src=\'js/jquery-3.0.0.min.js\'></script> -->");
document.writeln("<!-- <link type=\'text/css\' href=\'./css/index.css\' rel=\'stylesheet\' /> -->");
document.writeln("<style>");
document.writeln("  * {");
document.writeln("  margin: 0;");
document.writeln("  padding: 0;");
document.writeln("}");
document.writeln("li {");
document.writeln("  list-style: none;");
document.writeln("}");
document.writeln(".container-nav {");
document.writeln("  display: flex;");
document.writeln("  position: absolute;");
document.writeln("  /* background: #051A37; */");
document.writeln("  padding-left: 30px;");
document.writeln("  /* width: 95%; */");
document.writeln("  margin: 0 auto;");
document.writeln("  z-index: 99999;");
document.writeln("}");
document.writeln(".container-nav li {");
document.writeln("  font-size: 18px;");
document.writeln("  padding: 10px;");
document.writeln("}");
document.writeln("li a {");
document.writeln("  color: chocolate;");
document.writeln("  text-decoration: none;");
document.writeln("}");
document.writeln("li a:hover {");
document.writeln("  color: blue;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'\'>");
document.writeln("  <ul class=\'container-nav\'>");
document.writeln("    <li><a href=\'/\'>首页</a></li>");
document.writeln("    <li><a href=\'../navigation\'>分类</a></li>");
document.writeln("  </ul>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln(" /**");
document.writeln("  * html转换成js");
document.writeln("  * http://tool.chinaz.com/Tools/Html_Js.aspx");
document.writeln(" */");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");